spring.application.name=Stork

spring.datasource.url=jdbc:mysql://localhost:3306/distributed_fs
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true